language: node_js
sudo: required
services:
- docker
cache:
  directories:
  - node_modules
node_js:
- 6
before_install:
- cd api/
- npm install -g node-gyp
before_script:
- npm install -g standard
- docker-compose build
- docker-compose up -d
- sleep 3
- mongo "localhost:27017/nodetest1" --eval "db.dropDatabase();"
script:
- npm test
after_success: 
after_script:
- docker-compose kill
deploy:
  provider: releases
  api_key:
    secure: HYpwfQQ0WTjA5LffVUJNYFT9j+zsFowepfNKfns3ysfpKQikQTlw6Mqg4yGQ4i8H76ArufbqXjGeiVWZnxfDOUK7JUuUc2keIcijZMocx4uUKJvJte/KqKZhT7WvLPabPjfAXP3KXGZaVO8EjrcwaAFU2v3dSLAufjBI19cMCHF9f1KeMiBnNx6iBvkxMFIYHHnEl5IesnN/V6ewEsCuTTGKJVsnhDpCG3jVXWg/LtII5ndcuPjlQU0Fv+PEJXdwn01bdO0vU7jlsCQ3u3I+jsbh6VHLHzgnUxkc2F2M42OQk4W/+4FG3c0cok2g668KdnQ6+e46SHWdcNFtYcAuvzOrhg/osfpC3ZqHD25zb87N9yhkB5cq/X/NhrF/W6DdxrN2LneA9UxvmyL2KcYpq739mxC0ngO4W8its0+j6lCWZcCAcWn5vvVNzOhc2lYtaKLLhVKRUxl25wFafAjrVcEBdWPcQJdmkRRKV9MdNW8sOn/wFfyvjvNAtWXMjOyvIHaodnoCu2sWo7WVWn7vTNljmG8tHgbkoej1ZlzeuUn2F4lK3+4NU0cElQVVAirehcZ3kzeDQdz5mRrjzXmjk2Q+R51OsbFzfMr7lHBqCFU5H4fBnW9LOsMySsmlHwumHkGWcRvicfgczLIa5ZinMKBk+SrTGe42GKKqwNyXl4M=
  file: release.tgz
  on:
    branch: master
    tags: true
    repo: ElPenguinator/travistest